apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-mongo-depl
spec:
  selector:
    matchLabels:
      app: profile-mongo
  template:
    metadata:
      labels:
        app: profile-mongo
    spec:
      containers:
      - name: profile-mongo
        image: mongo
        volumeMounts:
        - mountPath: /data/db
          name: profile-mongo-pv-claim
      volumes:
      - name: profile-mongo-pv-claim
        persistentVolumeClaim:
          claimName: profile-mongo-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: profile-mongo-srv
spec:
  selector:
    app: profile-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
